import React from "react";
import SevenDayHero from "../components/SevenDayExp/SevenDayHero";
import GalleryToggle from "../components/SevenDayExp/GalleryToggle";
import Highlights from "../components/SevenDayExp/Highlights";
import SevenDayPricing from "../components/SevenDayExp/SevenDayPricing";
import SevenDayHeading from "../components/SevenDayExp/SevenDayHeading";
import { SEO } from "../seo/SEO";
import { SITE_URL } from "../seo/siteMeta";
import { useLocation } from "react-router-dom";

const sevenDayJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebPage",
      "@id": "https://www.superstar-yacht.com/seven-day-experience#webpage",
      "url": "https://www.superstar-yacht.com/seven-day-experience",
      "name": "Seven Day Yacht Charter Experience | 112’ Superstar Luxury Superyacht Florida",
      "description": "Experience a seven-day fully crewed luxury yacht charter aboard the 112’ Superstar. This all-inclusive Florida yacht vacation explores Miami, the Florida Keys, and the Dry Tortugas with private chef service, premium accommodations, and curated multi-day cruising itineraries.",
      "keywords": [
        "multi-day yacht charter Florida",
    "multi-day yacht charter Florida Gulf Coast",
    "multi-day yacht charter Sarasota",
    "multi-day yacht charter St.Petersburg",
    "multi-day yacht charter St.Pete",
    "multi-day yacht charter Tampa Bay",
    "multi-day yacht charter Tampa",
    "multi-day yacht charter Anna Maria",
    "multi-day yacht charter Anna Maria Island",
    "multi-day yacht charter Gulf Coast",
    "multi-day yacht charter Boca Grande",
    "multi-day yacht charter Key West",
    "multi-day yacht charter Captiva Island",
    "multi-day yacht charter Dry Tortugas",
    "multi-day yacht charter Fort Myers",
    "multi-day yacht charter Egmont Key",
    "multi-day yacht charter Longboat Key",
    "multi-day yacht charter Florida Keys",
    "multi-day yacht charter Miami",
    "overnight yacht charter Florida",
    "overnight yacht charter Florida Gulf Coast",
    "overnight yacht charter Sarasota",
    "overnight yacht charter St.Petersburg",
    "overnight yacht charter St.Pete",
    "overnight yacht charter Tampa Bay",
    "overnight yacht charter Tampa",
    "overnight yacht charter Anna Maria",
    "overnight yacht charter Anna Maria Island",
    "overnight yacht charter Gulf Coast",
    "overnight yacht charter Boca Grande",
    "overnight yacht charter Key West",
    "overnight yacht charter Captiva Island",
    "overnight yacht charter Dry Tortugas",
    "overnight yacht charter Fort Myers",
    "overnight yacht charter Egmont Key",
    "overnight yacht charter Longboat Key",
    "overnight yacht charter Florida Keys",
    "overnight yacht charter Miami",
    "luxury yacht rental Florida",
    "luxury yacht rental Gulf Coast",
    "luxury yacht rental Sarasota",
    "luxury yacht rental Tampa Bay",
    "luxury yacht rental St. Petersburg",
    "luxury yacht rental St. Pete",
    "luxury yacht rental Boca Grande",
    "luxury yacht rental Key West",
    "luxury yacht rental Captiva Island",
    "luxury yacht rental Dry Tortugas",
    "luxury yacht rental Fort Myers",
    "luxury yacht rental Egmont Key",
    "luxury yacht rental Longboat Key",
    "luxury yacht rental Florida Keys",
    "luxury yacht rental Miami",
    "private boat charters Florida",
    "private boat charters Gulf Coast",
    "private boat charters Sarasota",
    "private boat charters Tampa Bay",
    "private boat charters St. Petersburg",
    "private boat charters St. Pete",
    "private boat charters Boca Grande",
    "private boat charters Key West",
    "private boat charters Captiva Island",
    "private boat charters Dry Tortugas",
    "private boat charters Fort Myers",
    "private boat charters Egmont Key",
    "private boat charters Longboat Key",
    "private boat charters Florida Keys",
    "private boat charters Miami",
    "week-long boat rental Florida",
    "crewed yacht charters Florida",
    "crewed yacht charters Florida Gulf Coast",
    "crewed yacht charters Sarasota",
    "crewed yacht charters St.Petersburg",
    "crewed yacht charters St.Pete",
    "crewed yacht charters Tampa Bay",
    "crewed yacht charters Tampa",
    "crewed yacht charters Anna Maria",
    "crewed yacht charters Anna Maria Island",
    "crewed yacht charters Gulf Coast",
    "crewed yacht charters Boca Grande",
    "crewed yacht charters Key West",
    "crewed yacht charters Captiva Island",
    "crewed yacht charters Dry Tortugas",
    "crewed yacht charters Fort Myers",
    "crewed yacht charters Egmont Key",
    "crewed yacht charters Longboat Key",
    "crewed yacht charters Florida Keys",
    "crewed yacht charters Miami",
    "crewed superyacht charters Florida",
    "crewed superyacht charters Florida Gulf Coast",
    "crewed superyacht charters Sarasota",
    "crewed superyacht charters St.Petersburg",
    "crewed superyacht charters St.Pete",
    "crewed superyacht charters Tampa Bay",
    "crewed superyacht charters Tampa",
    "crewed superyacht charters Anna Maria",
    "crewed superyacht charters Anna Maria Island",
    "crewed superyacht charters Gulf Coast",
    "crewed superyacht charters Boca Grande",
    "crewed superyacht charters Key West",
    "crewed superyacht charters Captiva Island",
    "crewed superyacht charters Dry Tortugas",
    "crewed superyacht charters Fort Myers",
    "crewed superyacht charters Egmont Key",
    "crewed superyacht charters Longboat Key",
    "crewed superyacht charters Florida Keys",
    "crewed superyacht charters Miami",
    "superyacht charters Florida",
    "superyacht charters Florida Gulf Coast",
    "superyacht charters Sarasota",
    "superyacht charters St.Petersburg",
    "superyacht charters St.Pete",
    "superyacht charters Tampa Bay",
    "superyacht charters Tampa",
    "superyacht charters Anna Maria",
    "superyacht charters Anna Maria Island",
    "superyacht charters Gulf Coast",
    "superyacht charters Boca Grande",
    "superyacht charters Key West",
    "superyacht charters Captiva Island",
    "superyacht charters Dry Tortugas",
    "superyacht charters Fort Myers",
    "superyacht charters Egmont Key",
    "superyacht charters Longboat Key",
    "superyacht charters Florida Keys",
    "superyacht charters Miami",
    "superyacht excursion Florida",
    "superyacht excursion Florida Gulf Coast",
    "superyacht excursion Sarasota",
    "superyacht excursion St.Petersburg",
    "superyacht excursion St.Pete",
    "superyacht excursion Tampa Bay",
    "superyacht excursion Tampa",
    "superyacht excursion Anna Maria",
    "superyacht excursion Anna Maria Island",
    "superyacht excursion Gulf Coast",
    "superyacht excursion Boca Grande",
    "superyacht excursion Key West",
    "superyacht excursion Captiva Island",
    "superyacht excursion Dry Tortugas",
    "superyacht excursion Fort Myers",
    "superyacht excursion Egmont Key",
    "superyacht excursion Longboat Key",
    "superyacht excursion Florida Keys",
    "superyacht excursion Miami",
    "private chef yacht charter",
    "all-inclusive yacht vacation",
    "Dry Tortugas boat trip",
    "Florida Keys sailing charter",
    "private chef yacht charter",
    "all-inclusive yacht vacation",
    "112 foot yacht charter Florida",
    "112’ superyacht rental Miami",
    "fully crewed superyacht Florida",
    "luxury crewed yacht charter",
    "private superyacht charter Florida Keys",
    "corporate yacht charter Florida",
    "birthday yacht charter Miami",
    "bachelor party yacht charter Florida",
    "luxury family yacht vacation Florida",
    "extended yacht charter Florida Gulf Coast",
    "4 hour yacht charter Florida",
    "6 hour yacht charter Florida",
    "8 hour yacht charter Florida",
    "1 day yacht charter Florida",
    "2 day yacht charter Florida",
    "3 day yacht charter Florida",
    "4 day yacht charter Florida",
    "5 day yacht charter Florida",
    "6 day yacht charter Florida",
    "7 day yacht charter Florida",
    "4 hour yacht charter Florida",
    "6 hour yacht charter Florida",
    "8 hour yacht charter Florida",
    "1 day superyacht charter Florida",
    "2 day superyacht charter Florida",
    "3 day superyacht charter Florida",
    "4 day superyacht charter Florida",
    "5 day superyacht charter Florida",
    "6 day superyacht charter Florida",
    "7 day superyacht charter Florida",
      "Miami to Bimini yacht charter",
    "Sarasota to Key West yacht charter",
    "St.Petersburg to Key West yacht charter",
    "St.Pete to Key West yacht charter",
    "Tampa Bay to Key West yacht charter",
    "Anna Maria to Key West yacht charter",
    "Sarasota to Boca Grande yacht charter",
    "St.Petersburg to Boca Grande yacht charter",
    "St.Pete to Boca Grande yacht charter",
    "Tampa Bay to Boca Grande yacht charter",
    "Anna Maria to Boca Grande yacht charter",
    "Naples to Boca Grande yacht charter",
    "Naples Yacht Charter",
    "Fort Myers Yacht Charter",
    "Boca Grande Yacht Charter",
    "Dry Tortugas Yacht Charter",
    "Dry Tortugas National Park Yacht Charter",
    "Captiva Island Yacht Charter",
    "Sarasota Yacht Charter",
    "St. Petersburg Island Yacht Charter",
    "St.Pete Yacht Charter",
    "Anna Maria Yacht Charter",
    "Tampa Bay Yacht Charter",
    "Dry Tortugas boat trip",
    "Naples boat trip",
    "Fort Myers boat trip",
    "Boca Grande boat trip",
    "Dry Tortugas National Park boat trip",
    "Captiva Island boat trip",
    "Sarasota boat trip",
    "St. Petersburg Island boat trip",
    "St.Pete boat trip",
    "Anna Maria boat trip",
    "Tampa Bay boat trip",
    "Florida Keys sailing charter",
    "overnight yacht charter Florida",
    "week-long boat rental Florida",
    "luxury yacht rental Miami",
    "private boat charters Florida Keys",
    "all-inclusive yacht vacation Florida",
    "crewed yacht charter Bahamas",
    "private chef yacht charter",
    "superyacht excursion Florida",
    "Miami to Bimini yacht charter",
    "Dry Tortugas boat trip",
    "Fort Lauderdale yacht rental",
    "Florida Keys sailing charter",
    "extended yacht vacation Florida",
    "extended yacht vacation",
    "extended yacht vacation Sarasota",
    "extended yacht vacation Tampa Bay",
    "extended yacht vacation St. Petersburg",
    "extended yacht vacation St. Pete",
    "extended yacht vacation Boca Grande",
    "extended yacht vacation Key West",
    "extended yacht vacation Captiva Island",
    "extended yacht vacation Dry Tortugas",
    "extended yacht vacation Fort Myers",
    "extended yacht vacation Egmont Key",
    "extended yacht vacation Longboat Key",
    "extended yacht vacation Florida Keys",
    "extended yacht vacation Miami",
    "private overnight yacht charter",
    "private overnight yacht Sarasota",
    "private overnight yacht Tampa Bay",
    "private overnight yacht St. Petersburg",
    "private overnight yacht St. Pete",
    "private overnight yacht Boca Grande",
    "private overnight yacht Key West",
    "private overnight yacht Captiva Island",
    "private overnight yacht Dry Tortugas",
    "private overnight yacht Fort Myers",
    "private overnight yacht Egmont Key",
    "private overnight yacht Longboat Key",
    "private overnight yacht Florida Keys",
    "private overnight yacht Miami",
    "custom multi-day yacht itinerary",
    "Florida Gulf Coast yacht charter"
      ],
      "mainEntity": {
        "@id": "https://www.superstar-yacht.com/seven-day-experience#service"
      }
    },
    {
      "@type": "Service",
      "@id": "https://www.superstar-yacht.com/seven-day-experience#service",
      "name": "Seven Day Charter – 112’ Superstar Yacht",
      "description": "A seven-day luxury superyacht charter aboard the 112’ Superstar featuring a professional captain and crew, private chef dining, luxury stateroom accommodations, and custom cruising itineraries throughout Miami, the Florida Keys, Gulf Coast, and Dry Tortugas.",
      "provider": {
        "@type": "Organization",
        "name": "Kokomo Yachts",
        "url": "https://www.superstar-yacht.com/"
      },
      "areaServed": {
        "@type": "Place",
        "name": "Florida, United States"
      },
      "offers": {
        "@type": "Offer",
        "url": "https://www.superstar-yacht.com/seven-day-experience",
        "price": "67999",
        "priceCurrency": "USD",
        "availability": "https://schema.org/InStock",
        "itemOffered": {
          "@type": "Service",
          "name": "Seven Day Luxury Yacht Charter – 112’ Superstar"
        }
      }
    }
  ]
}
const SevenDayExp = () => {
  const { pathname } = useLocation();
  return (
    <>
      <SEO
        title="Week Long Superyacht Experience on Florida’s Gulf Coast"
        description="Indulge in a week-long yacht vacation on 112’ Superstar, a fully crewed 112’ superyacht. Sail Dry Tortugas, Captiva Island, Fort Myers, Miami, the Florida Keys & beyond in unmatched luxury."
        canonical={`${SITE_URL}${pathname}`}
        jsonLd={sevenDayJsonLd}
      />
      <div className="w-full">
        <SevenDayHero />
        <SevenDayHeading />
        <GalleryToggle />
        <Highlights />
        <SevenDayPricing />
      </div>
    </>
  );
};

export default SevenDayExp;
